//! Bounded, fail-safe retention for local snapshots, exports, and audit files.
//!
//! Planning is read-only and deterministic. Deletion revalidates every
//! candidate as a regular file and never follows symlinks. Only filenames
//! generated by `FWDeck` are eligible; unknown files are ignored.

use std::path::{Path, PathBuf};
use std::time::SystemTime;

use crate::config::{FileRetentionConfig, RetentionConfig};

/// Which local-state collection a retention operation may inspect or prune.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RetentionScope {
    /// Snapshots, exports, and audit files.
    All,
    /// Saved firewall snapshots only.
    Snapshots,
    /// Versioned staged-plan exports only.
    Exports,
    /// Rotated audit files only; the active audit file is always protected.
    Audit,
}

/// Why a file is eligible for pruning.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PruneReason {
    /// It exceeds the configured count limit.
    Count,
    /// It exceeds the configured age limit.
    Age,
    /// It exceeds both count and age limits.
    CountAndAge,
}

impl PruneReason {
    /// Stable operator-facing reason label.
    #[must_use]
    pub const fn label(self) -> &'static str {
        match self {
            Self::Count => "count limit",
            Self::Age => "age limit",
            Self::CountAndAge => "count and age limits",
        }
    }
}

/// One regular, app-owned file selected by the retention planner.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PruneCandidate {
    /// Absolute path selected for removal.
    pub path: PathBuf,
    /// File size observed while planning.
    pub bytes: u64,
    /// Policy threshold selecting the file.
    pub reason: PruneReason,
}

/// Read-only retention status for one local-state collection.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct CollectionPlan {
    /// Number of recognized regular files.
    pub files: usize,
    /// Total size of recognized regular files.
    pub bytes: u64,
    /// Number of pinned/protected files.
    pub protected: usize,
    /// Files eligible for pruning, oldest first.
    pub candidates: Vec<PruneCandidate>,
}

/// Complete read-only retention plan.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct RetentionPlan {
    /// Snapshot status and candidates.
    pub snapshots: CollectionPlan,
    /// Export status and candidates.
    pub exports: CollectionPlan,
    /// Audit status and candidates.
    pub audit: CollectionPlan,
}

impl RetentionPlan {
    /// Total files selected by this plan.
    #[must_use]
    pub fn candidate_count(&self) -> usize {
        self.snapshots.candidates.len()
            + self.exports.candidates.len()
            + self.audit.candidates.len()
    }

    fn candidates(&self) -> impl Iterator<Item = &PruneCandidate> {
        self.snapshots
            .candidates
            .iter()
            .chain(&self.exports.candidates)
            .chain(&self.audit.candidates)
    }
}

/// Result of applying a retention plan.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct PruneReport {
    /// Plan that was revalidated and applied.
    pub plan: RetentionPlan,
    /// Paths removed successfully.
    pub removed: Vec<PathBuf>,
    /// Bytes reclaimed according to pre-delete metadata.
    pub reclaimed_bytes: u64,
    /// Candidates that became pinned after planning and were preserved.
    pub skipped_protected: Vec<PathBuf>,
    /// Per-file or directory-sync failures. Other candidates are still tried.
    pub failures: Vec<String>,
}

#[derive(Debug, Clone)]
struct FileItem {
    path: PathBuf,
    bytes: u64,
    modified: SystemTime,
    protected: bool,
}

/// Builds a read-only plan using the current clock.
pub fn plan(config: &RetentionConfig, scope: RetentionScope) -> Result<RetentionPlan, String> {
    plan_at(config, scope, SystemTime::now())
}

/// Applies a freshly built plan. Candidate types are revalidated immediately
/// before removal, and directory entries are synced after successful deletes.
pub fn prune(config: &RetentionConfig, scope: RetentionScope) -> Result<PruneReport, String> {
    let plan = plan(config, scope)?;
    Ok(apply_plan(plan))
}

fn apply_plan(plan: RetentionPlan) -> PruneReport {
    let candidates: Vec<PruneCandidate> = plan.candidates().cloned().collect();
    let mut report = PruneReport {
        plan,
        ..PruneReport::default()
    };
    let mut touched = std::collections::BTreeSet::new();

    for candidate in candidates {
        if snapshot_is_pinned(&candidate.path) {
            report.skipped_protected.push(candidate.path);
            continue;
        }
        match std::fs::symlink_metadata(&candidate.path) {
            Ok(metadata) if metadata.file_type().is_file() => {
                match std::fs::remove_file(&candidate.path) {
                    Ok(()) => {
                        report.reclaimed_bytes =
                            report.reclaimed_bytes.saturating_add(candidate.bytes);
                        if let Some(parent) = candidate.path.parent() {
                            touched.insert(parent.to_path_buf());
                        }
                        report.removed.push(candidate.path);
                    }
                    Err(err) if err.kind() == std::io::ErrorKind::NotFound => {}
                    Err(err) => report
                        .failures
                        .push(format!("remove {}: {err}", candidate.path.display())),
                }
            }
            Ok(_) => report.failures.push(format!(
                "refused changed non-regular candidate {}",
                candidate.path.display()
            )),
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => {}
            Err(err) => report
                .failures
                .push(format!("revalidate {}: {err}", candidate.path.display())),
        }
    }

    for dir in touched {
        if let Err(err) = super::state_file::sync_dir(&dir) {
            report
                .failures
                .push(format!("sync {}: {err}", dir.display()));
        }
    }
    report
}

fn plan_at(
    config: &RetentionConfig,
    scope: RetentionScope,
    now: SystemTime,
) -> Result<RetentionPlan, String> {
    let Some(root) = crate::bootstrap::state_dir() else {
        return Ok(RetentionPlan::default());
    };
    plan_at_root(config, scope, now, &root)
}

fn plan_at_root(
    config: &RetentionConfig,
    scope: RetentionScope,
    now: SystemTime,
    root: &Path,
) -> Result<RetentionPlan, String> {
    let mut result = RetentionPlan::default();
    if matches!(scope, RetentionScope::All | RetentionScope::Snapshots) {
        let items = discover(&root.join("snapshots"), is_snapshot_name, |dir, name| {
            is_regular_file(&dir.join(pin_name(name)))
        })?;
        result.snapshots = plan_files(items, config.snapshots, now);
    }
    if matches!(scope, RetentionScope::All | RetentionScope::Exports) {
        let items = discover(&root.join("exports"), is_export_name, |_, _| false)?;
        result.exports = plan_files(items, config.exports, now);
    }
    if matches!(scope, RetentionScope::All | RetentionScope::Audit) {
        let items = discover(root, is_audit_name, |_, name| name == "audit.jsonl")?;
        result.audit = plan_audit(items, config.audit.max_files);
    }
    Ok(result)
}

fn discover(
    dir: &Path,
    matches_name: impl Fn(&str) -> bool,
    is_protected: impl Fn(&Path, &str) -> bool,
) -> Result<Vec<FileItem>, String> {
    let entries = match std::fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Ok(Vec::new()),
        Err(err) => return Err(format!("read retention directory {}: {err}", dir.display())),
    };
    let mut items = Vec::new();
    for entry in entries {
        let entry = entry.map_err(|err| format!("read {} entry: {err}", dir.display()))?;
        let name = entry.file_name().to_string_lossy().into_owned();
        if !matches_name(&name) {
            continue;
        }
        let metadata = std::fs::symlink_metadata(entry.path())
            .map_err(|err| format!("metadata {}: {err}", entry.path().display()))?;
        if !metadata.file_type().is_file() {
            continue;
        }
        let modified = metadata
            .modified()
            .map_err(|err| format!("modified time {}: {err}", entry.path().display()))?;
        items.push(FileItem {
            path: entry.path(),
            bytes: metadata.len(),
            modified,
            protected: is_protected(dir, &name),
        });
    }
    Ok(items)
}

fn plan_files(
    mut items: Vec<FileItem>,
    policy: FileRetentionConfig,
    now: SystemTime,
) -> CollectionPlan {
    items.sort_by(|a, b| {
        b.modified
            .cmp(&a.modified)
            .then_with(|| b.path.cmp(&a.path))
    });
    let files = items.len();
    let bytes = items
        .iter()
        .fold(0u64, |total, item| total.saturating_add(item.bytes));
    let protected = items.iter().filter(|item| item.protected).count();
    let mut unprotected_rank = 0usize;
    let mut candidates = Vec::new();
    for item in items {
        if item.protected {
            continue;
        }
        let protected_by_floor = unprotected_rank < policy.min_keep;
        let over_count = unprotected_rank >= policy.max_count;
        let over_age = now
            .duration_since(item.modified)
            .is_ok_and(|age| age >= policy.max_age);
        unprotected_rank = unprotected_rank.saturating_add(1);
        if protected_by_floor || (!over_count && !over_age) {
            continue;
        }
        candidates.push(PruneCandidate {
            path: item.path,
            bytes: item.bytes,
            reason: reason(over_count, over_age),
        });
    }
    candidates.reverse();
    CollectionPlan {
        files,
        bytes,
        protected,
        candidates,
    }
}

fn plan_audit(mut items: Vec<FileItem>, max_files: usize) -> CollectionPlan {
    items.sort_by(|a, b| {
        b.modified
            .cmp(&a.modified)
            .then_with(|| b.path.cmp(&a.path))
    });
    let files = items.len();
    let bytes = items
        .iter()
        .fold(0u64, |total, item| total.saturating_add(item.bytes));
    let protected = items.iter().filter(|item| item.protected).count();
    let rotated_limit = max_files.saturating_sub(protected);
    let mut rank = 0usize;
    let mut candidates = Vec::new();
    for item in items {
        if item.protected {
            continue;
        }
        if rank >= rotated_limit {
            candidates.push(PruneCandidate {
                path: item.path,
                bytes: item.bytes,
                reason: PruneReason::Count,
            });
        }
        rank = rank.saturating_add(1);
    }
    candidates.reverse();
    CollectionPlan {
        files,
        bytes,
        protected,
        candidates,
    }
}

fn reason(over_count: bool, over_age: bool) -> PruneReason {
    match (over_count, over_age) {
        (true, true) => PruneReason::CountAndAge,
        (true, false) => PruneReason::Count,
        (false, _) => PruneReason::Age,
    }
}

fn is_regular_file(path: &Path) -> bool {
    std::fs::symlink_metadata(path).is_ok_and(|metadata| metadata.file_type().is_file())
}

fn snapshot_is_pinned(path: &Path) -> bool {
    let Some(name) = path.file_name().and_then(|name| name.to_str()) else {
        return false;
    };
    if !is_snapshot_name(name)
        || path
            .parent()
            .and_then(Path::file_name)
            .is_none_or(|parent| parent != "snapshots")
    {
        return false;
    }
    path.parent()
        .is_some_and(|dir| is_regular_file(&dir.join(pin_name(name))))
}

pub(crate) fn is_snapshot_name(name: &str) -> bool {
    name.strip_prefix("snapshot-")
        .and_then(|name| name.strip_suffix(".json"))
        .is_some_and(|stem| numeric_stem(stem, 2))
}

pub(crate) fn is_export_name(name: &str) -> bool {
    ["sh", "json", "yml"].iter().any(|extension| {
        name == format!("staged-plan.{extension}")
            || name
                .strip_prefix("staged-plan-")
                .and_then(|name| name.strip_suffix(&format!(".{extension}")))
                .is_some_and(|stem| numeric_stem(stem, 2))
    })
}

fn is_audit_name(name: &str) -> bool {
    name == "audit.jsonl"
        || name
            .strip_prefix("audit-")
            .and_then(|name| name.strip_suffix(".jsonl"))
            .is_some_and(|stem| numeric_stem(stem, 2))
        || name.strip_prefix("audit.jsonl.").is_some_and(|suffix| {
            !suffix.is_empty() && suffix.bytes().all(|byte| byte.is_ascii_digit())
        })
}

pub(crate) fn pin_name(snapshot_name: &str) -> String {
    format!("{snapshot_name}.pin")
}

fn numeric_stem(stem: &str, max_parts: usize) -> bool {
    let mut parts = stem.split('-');
    let mut count = 0usize;
    for part in parts.by_ref() {
        count = count.saturating_add(1);
        if count > max_parts || part.is_empty() || !part.bytes().all(|byte| byte.is_ascii_digit()) {
            return false;
        }
    }
    count > 0
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;
    use std::time::UNIX_EPOCH;

    fn item(name: &str, age_days: u64, protected: bool) -> FileItem {
        FileItem {
            path: PathBuf::from(name),
            bytes: 10,
            modified: UNIX_EPOCH + std::time::Duration::from_secs((100 - age_days) * 86_400),
            protected,
        }
    }

    #[test]
    fn age_and_count_respect_minimum_and_pins() {
        let now = UNIX_EPOCH + std::time::Duration::from_secs(100 * 86_400);
        let policy = FileRetentionConfig {
            max_count: 3,
            max_age: std::time::Duration::from_secs(30 * 86_400),
            min_keep: 2,
        };
        let plan = plan_files(
            vec![
                item("new", 1, false),
                item("floor", 40, false),
                item("old", 50, false),
                item("count", 60, false),
                item("pinned", 99, true),
            ],
            policy,
            now,
        );
        assert_eq!(plan.protected, 1);
        let names: Vec<_> = plan
            .candidates
            .iter()
            .map(|candidate| candidate.path.to_string_lossy().into_owned())
            .collect();
        assert_eq!(names, vec!["count", "old"]);
        assert_eq!(plan.candidates[0].reason, PruneReason::CountAndAge);
        assert_eq!(plan.candidates[1].reason, PruneReason::Age);
    }

    #[test]
    fn audit_limit_counts_the_protected_active_file() {
        let plan = plan_audit(
            vec![
                item("audit.jsonl", 0, true),
                item("audit-3.jsonl", 1, false),
                item("audit-2.jsonl", 2, false),
                item("audit-1.jsonl", 3, false),
            ],
            3,
        );
        assert_eq!(plan.protected, 1);
        assert_eq!(plan.candidates.len(), 1);
        assert_eq!(plan.candidates[0].path, PathBuf::from("audit-1.jsonl"));
    }

    #[test]
    fn strict_name_matching_rejects_unknown_and_traversal_names() {
        assert!(is_snapshot_name("snapshot-1700000000000.json"));
        assert!(is_snapshot_name("snapshot-1700000000000-1.json"));
        assert!(!is_snapshot_name("../snapshot-1.json"));
        assert!(!is_snapshot_name("snapshot-x.json"));
        assert!(is_export_name("staged-plan-1700000000000.yml"));
        assert!(is_export_name("staged-plan.json"));
        assert!(!is_export_name("customer-plan.json"));
        assert!(is_audit_name("audit.jsonl.1"));
        assert!(is_audit_name("audit-1700000000000.jsonl"));
        assert!(!is_audit_name("audit-copy.jsonl"));
    }

    #[cfg(unix)]
    #[test]
    fn discovery_ignores_symlinks_even_when_the_name_matches() {
        use std::os::unix::fs::symlink;

        let dir = std::env::temp_dir().join(format!("fwdeck-retention-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let target = dir.join("target");
        std::fs::write(&target, "secret").unwrap();
        symlink(&target, dir.join("snapshot-1.json")).unwrap();
        let items = discover(&dir, is_snapshot_name, |_, _| false).unwrap();
        assert!(items.is_empty());
        let _ = std::fs::remove_dir_all(dir);
    }

    #[test]
    fn pruning_revalidates_and_removes_only_planned_regular_files() {
        let dir = std::env::temp_dir().join(format!("fwdeck-prune-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let old = dir.join("snapshot-1.json");
        std::fs::write(&old, "old").unwrap();
        let candidate = PruneCandidate {
            path: old.clone(),
            bytes: 3,
            reason: PruneReason::Age,
        };
        let plan = RetentionPlan {
            snapshots: CollectionPlan {
                files: 1,
                bytes: 3,
                protected: 0,
                candidates: vec![candidate],
            },
            ..RetentionPlan::default()
        };
        let report = apply_plan(plan);
        assert_eq!(report.removed, vec![old]);
        assert_eq!(report.reclaimed_bytes, 3);
        assert!(report.failures.is_empty());
        assert!(!dir.join("snapshot-1.json").exists());
        let _ = std::fs::remove_dir_all(dir);
    }

    #[cfg(unix)]
    #[test]
    fn pruning_refuses_a_candidate_replaced_with_a_symlink() {
        use std::os::unix::fs::symlink;

        let dir = std::env::temp_dir().join(format!("fwdeck-prune-race-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let target = dir.join("target");
        let candidate_path = dir.join("snapshot-1.json");
        std::fs::write(&target, "keep").unwrap();
        symlink(&target, &candidate_path).unwrap();
        let plan = RetentionPlan {
            snapshots: CollectionPlan {
                files: 1,
                bytes: 4,
                protected: 0,
                candidates: vec![PruneCandidate {
                    path: candidate_path,
                    bytes: 4,
                    reason: PruneReason::Age,
                }],
            },
            ..RetentionPlan::default()
        };
        let report = apply_plan(plan);
        assert!(report.removed.is_empty());
        assert_eq!(report.failures.len(), 1);
        assert_eq!(std::fs::read_to_string(&target).unwrap(), "keep");
        let _ = std::fs::remove_dir_all(dir);
    }

    #[test]
    fn apply_rechecks_a_snapshot_pin_created_after_planning() {
        let root = std::env::temp_dir().join(format!("fwdeck-prune-pin-{}", std::process::id()));
        let dir = root.join("snapshots");
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("snapshot-1.json");
        std::fs::write(&path, "keep").unwrap();
        let plan = RetentionPlan {
            snapshots: CollectionPlan {
                files: 1,
                bytes: 4,
                protected: 0,
                candidates: vec![PruneCandidate {
                    path: path.clone(),
                    bytes: 4,
                    reason: PruneReason::Age,
                }],
            },
            ..RetentionPlan::default()
        };
        std::fs::write(dir.join(pin_name("snapshot-1.json")), "pinned").unwrap();
        let report = apply_plan(plan);
        assert!(report.removed.is_empty());
        assert_eq!(report.skipped_protected, vec![path.clone()]);
        assert!(path.exists());
        let _ = std::fs::remove_dir_all(root);
    }

    #[test]
    fn filesystem_plan_ignores_unknown_files_and_honors_pin_markers() {
        let root = std::env::temp_dir().join(format!("fwdeck-plan-root-{}", std::process::id()));
        let snapshots = root.join("snapshots");
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(&snapshots).unwrap();
        std::fs::write(snapshots.join("snapshot-1.json"), "one").unwrap();
        std::fs::write(snapshots.join("snapshot-2.json"), "two").unwrap();
        std::fs::write(snapshots.join("snapshot-2.json.pin"), "pinned").unwrap();
        std::fs::write(snapshots.join("customer-import.json"), "unknown").unwrap();
        let config = RetentionConfig {
            snapshots: FileRetentionConfig {
                max_count: 1,
                max_age: std::time::Duration::from_secs(1),
                min_keep: 0,
            },
            exports: FileRetentionConfig {
                max_count: 1,
                max_age: std::time::Duration::from_secs(1),
                min_keep: 0,
            },
            audit: crate::config::AuditRetentionConfig {
                max_files: 2,
                max_file_size: 1024,
            },
        };
        let plan = plan_at_root(
            &config,
            RetentionScope::Snapshots,
            SystemTime::now() + std::time::Duration::from_secs(2),
            &root,
        )
        .unwrap();
        assert_eq!(plan.snapshots.files, 2);
        assert_eq!(plan.snapshots.protected, 1);
        assert_eq!(plan.snapshots.candidates.len(), 1);
        assert_eq!(
            plan.snapshots.candidates[0]
                .path
                .file_name()
                .unwrap()
                .to_string_lossy(),
            "snapshot-1.json"
        );
        let _ = std::fs::remove_dir_all(root);
    }
}
